[project]
name = "buildfest25"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "inference-sdk>=0.12.0",
    "numpy>=1.26.4",
    "opencv-python>=4.10.0.84",
    "python-dotenv>=1.0.1",
    "ultralytics>=8.3.23",
]
